-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS dipsignal.dim_assets
(
    asset_id serial NOT NULL,
    symbol character varying(20) COLLATE pg_catalog."default" NOT NULL,
    asset_class character varying(20) COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default",
    static_metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dim_assets_pkey PRIMARY KEY (asset_id),
    CONSTRAINT dim_assets_symbol_key UNIQUE (symbol)
);

CREATE TABLE IF NOT EXISTS dipsignal.dim_date
(
    date_id integer NOT NULL,
    full_date date NOT NULL,
    year integer,
    quarter integer,
    month integer,
    week integer,
    day_of_week integer,
    day_name text COLLATE pg_catalog."default",
    is_weekend boolean,
    is_us_market_open boolean,
    is_crypto_open boolean DEFAULT true,
    CONSTRAINT dim_date_pkey PRIMARY KEY (date_id),
    CONSTRAINT dim_date_full_date_key UNIQUE (full_date)
);

CREATE TABLE IF NOT EXISTS dipsignal.fact_ai_analysis
(
    analysis_id serial NOT NULL,
    asset_id integer,
    date date NOT NULL,
    model_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    trend_signal character varying(20) COLLATE pg_catalog."default",
    key_levels jsonb,
    summary_text text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fact_ai_analysis_pkey PRIMARY KEY (analysis_id),
    CONSTRAINT fact_ai_analysis_asset_id_date_key UNIQUE (asset_id, date)
);

CREATE TABLE IF NOT EXISTS dipsignal.fact_asset_prices
(
    fact_id bigserial NOT NULL,
    asset_id serial NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    "interval" character varying(5) COLLATE pg_catalog."default" NOT NULL,
    price_open numeric(20, 8),
    price_high numeric(20, 8),
    price_low numeric(20, 8),
    price_close numeric(20, 8),
    volume numeric(30, 8),
    dynamic_metadata jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT fact_asset_prices_pkey PRIMARY KEY (fact_id),
    CONSTRAINT fact_asset_prices_asset_id_timestamp_interval_key UNIQUE (asset_id, "timestamp", "interval")
);

CREATE TABLE IF NOT EXISTS dipsignal.fact_macro_indicators
(
    date date NOT NULL,
    dxy numeric(10, 2),
    sp500 numeric(10, 2),
    cpi numeric(10, 2),
    interest_rate numeric(10, 2),
    market_closed boolean,
    vix numeric(10, 2),
    treasury_10y numeric(10, 2),
    unemployment_rate numeric(10, 2),
    gdp numeric(20, 2),
    CONSTRAINT fact_macro_indicators_pkey PRIMARY KEY (date)
);

CREATE TABLE IF NOT EXISTS dipsignal.fact_macro_summary
(
    summary_id serial NOT NULL,
    date date NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL,
    model_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    summary_text text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    summary_short text COLLATE pg_catalog."default",
    CONSTRAINT fact_macro_summary_pkey PRIMARY KEY (summary_id),
    CONSTRAINT fact_macro_summary_date_key UNIQUE (date)
);

CREATE TABLE IF NOT EXISTS dipsignal.fact_news_articles
(
    article_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date date,
    source text COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default",
    summary text COLLATE pg_catalog."default",
    url text COLLATE pg_catalog."default",
    related_tickers jsonb DEFAULT '[]'::jsonb,
    CONSTRAINT fact_news_articles_pkey PRIMARY KEY (article_id),
    CONSTRAINT fact_news_articles_url_key UNIQUE (url)
);

CREATE TABLE IF NOT EXISTS dipsignal.fact_portfolio_recommendations
(
    recommendation_id serial NOT NULL,
    date date NOT NULL,
    risk_profile character varying(20) COLLATE pg_catalog."default" NOT NULL,
    model_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    allocation_stocks integer,
    allocation_crypto integer,
    allocation_commodities integer,
    top_picks jsonb NOT NULL,
    sector_exposure jsonb,
    diversification_score numeric(3, 1),
    correlation_analysis text COLLATE pg_catalog."default",
    overall_rationale text COLLATE pg_catalog."default",
    news_impact text COLLATE pg_catalog."default",
    risks jsonb,
    rebalance_frequency character varying(20) COLLATE pg_catalog."default",
    token_count integer,
    data_sources jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fact_portfolio_recommendations_pkey PRIMARY KEY (recommendation_id),
    CONSTRAINT fact_portfolio_recommendations_date_risk_key UNIQUE (date, risk_profile)
);

CREATE TABLE IF NOT EXISTS dipsignal.fact_sentiment_index
(
    date date NOT NULL,
    fgi_value bigint,
    classification text COLLATE pg_catalog."default",
    CONSTRAINT fact_sentiment_index_pkey PRIMARY KEY (date)
);

ALTER TABLE IF EXISTS dipsignal.fact_ai_analysis
    ADD CONSTRAINT fact_ai_analysis_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES dipsignal.dim_assets (asset_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dipsignal.fact_ai_analysis
    ADD CONSTRAINT fact_ai_analysis_date_fkey FOREIGN KEY (date)
    REFERENCES dipsignal.dim_date (full_date) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dipsignal.fact_asset_prices
    ADD CONSTRAINT fact_asset_prices_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES dipsignal.dim_assets (asset_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dipsignal.fact_macro_indicators
    ADD CONSTRAINT fk_macro_date FOREIGN KEY (date)
    REFERENCES dipsignal.dim_date (full_date) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fact_macro_indicators_pkey
    ON dipsignal.fact_macro_indicators(date);


ALTER TABLE IF EXISTS dipsignal.fact_macro_summary
    ADD CONSTRAINT fk_macro_summary_date FOREIGN KEY (date)
    REFERENCES dipsignal.dim_date (full_date) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_macro_summary_date
    ON dipsignal.fact_macro_summary(date);


ALTER TABLE IF EXISTS dipsignal.fact_news_articles
    ADD CONSTRAINT fk_news_date FOREIGN KEY (date)
    REFERENCES dipsignal.dim_date (full_date) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dipsignal.fact_portfolio_recommendations
    ADD CONSTRAINT fk_portfolio_date FOREIGN KEY (date)
    REFERENCES dipsignal.dim_date (full_date) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_portfolio_recommendations_date
    ON dipsignal.fact_portfolio_recommendations(date);


ALTER TABLE IF EXISTS dipsignal.fact_sentiment_index
    ADD CONSTRAINT fk_sentiment_date FOREIGN KEY (date)
    REFERENCES dipsignal.dim_date (full_date) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fact_sentiment_index_pkey
    ON dipsignal.fact_sentiment_index(date);

END;